"""empty message

Revision ID: 5a46bdc2fd4c
Revises: 7dc475b0b9bb
Create Date: 2022-02-03 21:07:09.417810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a46bdc2fd4c'
down_revision = '7dc475b0b9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('stock', 'fetch_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('fetch_time', sa.DATE(), nullable=True))
    op.drop_column('stock', 'time')
    # ### end Alembic commands ###
